### ISSUE TITLE
Please add support for configuring external keyservers like mit.edu

### ISSUE THREAD

**Issue by parvez** [whiteout-io/mail-html5#236]
Currently the CloudUrl setting is https://keys.whiteout.io. Do we or Can we have support for other keyservers? e.g. https://pgp.mit.edu/pks/lookup?op=get&search=billgates@gmail.com

**Comment by tanx** [comment]
@parvez no timeline on the Web Of Trust graph browser yet, but HKP server integration has been added in:

https://github.com/whiteout-io/mail-html5/tree/dev/WO-862

Basically the our keys.whiteout.io keyserver will fetch keys from pgp.mit.edu in case no key is available and tag the key object with a source attribute. The sync works both way, so keys are uploaded to pgp.mit.edu after the email address has been verified.

The client can't query pgp.mit.edu directly since the old pks servers don't support CORS headers required for cross-origin requests. That's why our key servers acts as a proxy.

The cool thing is that the user never has to worry about manually importing keys this way as keys will be fetched automatically during read/write of messages. We thought about displaying a dialog to let users confirm a hkp key, but decided on a TOFU (trust on first use) for ease of use. That way average whiteout users can write encrypted emails with technical GPG users and it will just work.

Closing this issue... the feature will be in the upcoming release.

**Comment by tanx** [comment]
v0.22.0 has been released and includes the HKP server integration ([release notes](https://github.com/whiteout-io/mail-html5/releases/tag/v0.22.0)).

You can install it here: https://whiteout.io/#product

We'll write a post on how this works in detail on our [blog](https://blog.whiteout.io/) soon. Looking forward to your feedback.
