### ISSUE TITLE
Resend

### ISSUE THREAD

**Issue by xokvictor** [whiteout-io/mail-html5#294]
It's comfortably  when i want resend new message to all 10 (for example) contacts which i add before, when I wrote first message.

**Comment by felixhammerl** [comment]
thanks for your suggestions! seems like you have invested quite a bunch of time into compiling that list and we're grateful for that! just one thing: instead of putting all of those up on github, could you please get in touch with us via support@whiteout.io? we like your stuff, it's just a loooooot of issues you just opened and maybe a little discussion might be a good thing here before we put this all up on github. looking forward to hearing from you!

**Comment by xokvictor** [comment]
OK! Sorry )
Resend all of my suggestions to support@whiteout.io?

**Comment by felixhammerl** [comment]
that would be really helpful, thanks a lot :)

**Comment by xokvictor** [comment]
ok, i do it after sleeping

**Comment by xokvictor** [comment]
@felixhammerl i resend all opened suggestions to support@whiteout.io
