### ISSUE TITLE
Mail list entries are slow to update

### ISSUE THREAD

**Issue by DejayRezme** [whiteout-io/mail-html5#364]
When you scroll down messages are initially blank and grey with a spinning circle. Ideally whiteout should first show the cached from / subject / date and then when the update from imap comes through you should add / remove emails. So that the cached local version of the emails shows up immediately.

**Comment by felixhammerl** [comment]
RE fetching from disk: That is actually what we're doing.
RE partial IMAP fetching: We did this before, but it deteriorates performance because of partially fetched mails where users wondered why they can't read an email when they're offline.

But we're working on improving the overall performance, which would also help to address this issue.
