### ISSUE TITLE
Add pgp options/wrong standard

### ISSUE THREAD

**Issue by iorek1988** [whiteout-io/mail-html5#382]
~~It would be very nice to have some more options in the process of generating the key, e.g. i would like to set the length of my key to 4096 bits. Maybe as a expert option not shown at first...~~
(sorry didn't notice that the issue was already there)

Also it would be nice to have the option to change the pgp standard to inline. I know its not »state of the art« but in fact a lot of people can not understand more than that. K9 and APG/openkeychain only show inline messages. Another problem seems to be, that you have a mistake in your encryption. adele-en@gnupp.de can not decrypt the message. If i copy the text of an email to another adress of me by hand into APG it errors with saying, that the integration of the encryption has an error. On my linux machine the decryption works fine...
Maybe the inline support could change the biggest problems...

wkr iorek

**Comment by felixhammerl** [comment]
hi, letting the **user** choose to send either as pgp/inline or pgp/mime is extremely bad user experience, since this is a decision most users will not be able to make. also, in the pgp community, the overwhelming majority is leaning towards deprecating pgp/inline and letting it rest in peace. pgp/mime is a properly standardized format, whereas pgp/inline is a shim that's broken more often than not.
