### ISSUE TITLE
Error message: Could not parse certificate list.

### ISSUE THREAD

**Issue by deltaman** [whiteout-io/mail-html5#385]
Hi,

When creating a new account on the first time I get the error message:
Could not parse certificate list.

When using IMAP with TLS(993), although this is working with Thunderbird.

Hugo

**Comment by ApfelUser** [comment]
:+1: Same error here.

**Comment by deltaman** [comment]
I have also testen the Certificate chain with the app SSL Detective, that app showed me that there was an intermediate certificate was not trusted. I have installed the COMODO certificate and testes again. Although the SSL Detective app showed me that the certificate chain was trusted, whiteout mail is still gives me the same error.

**Comment by deltaman** [comment]
After updating to version 1.2.0, login seems to succeed for IMAP:993.

Now I am getting the same error for SMTP STARTTLS

**Comment by felixhammerl** [comment]
On the desktop: Please use the [chrome app](https://chrome.google.com/webstore/detail/whiteout-mail/jjgghafhamholjigjoghcfcekhkonijg), as it supports native tls. 

On iOS/Android: Starting with version 1.2.0, we use the native TLS stack for TLS connections, NOT STARTTLS. 

The webapp and STARTTLS on iOS/Android default to using [forge](https://github.com/digitalbazaar/forge) because of this bug:

https://github.com/MobileChromeApps/mobile-chrome-apps/issues/532
https://github.com/MobileChromeApps/mobile-chrome-apps/issues/269
https://code.google.com/p/chromium/issues/detail?id=467677

Problem is: Google does not seem to care about fixing its API...

**Comment by deltaman** [comment]
Does this mean that if I want to use this app that I have to change the server configuration? So that SMTP to work with TLS?


Op 7 jul. 2015 om 11:30 heeft Felix Hammerl <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


On the desktop: Please use the chrome app<https://chrome.google.com/webstore/detail/whiteout-mail/jjgghafhamholjigjoghcfcekhkonijg>, as it supports native tls.

On iOS/Android: Starting with version 1.2.0, we use the native TLS stack for TLS connections, NOT STARTTLS.

The webapp and STARTTLS on iOS/Android default to using forge<https://github.com/digitalbazaar/forge> because of this bug:

MobileChromeApps/mobile-chrome-apps#532<https://github.com/MobileChromeApps/mobile-chrome-apps/issues/532>
MobileChromeApps/mobile-chrome-apps#269<https://github.com/MobileChromeApps/mobile-chrome-apps/issues/269>
https://code.google.com/p/chromium/issues/detail?id=467677

Problem is: Google does not seem to care about fixing its API...
